# Generated by Django 4.2.7 on 2023-12-10 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_employee_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('Мужской', 'М'), ('Женский', 'Ж')], default='Мужской', max_length=10),
        ),
    ]
