# Generated by Django 4.2.7 on 2023-12-11 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_employee_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery',
        ),
        migrations.AddField(
            model_name='order',
            name='courier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_delivering', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('completed', 'завершен'), ('cooking', 'готовится'), ('cancelled', 'отменен'), ('delivery', 'в доставке')], default='cooking', max_length=9),
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_work_day',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_work_day',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_cooking', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Delivery',
        ),
    ]
