# Generated by Django 4.2.7 on 2023-12-11 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_order_delivery_order_courier_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('Завершен', 'completed'), ('Готовится', 'cooking'), ('Отменён', 'cancelled'), ('Доставка', 'delivery')], default='Cамовывоз', max_length=9),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Завершен', 'completed'), ('Готовится', 'cooking'), ('Отменён', 'cancelled'), ('Доставка', 'delivery')], default='Готовится', max_length=9),
        ),
    ]
