# Generated by Django 4.2.7 on 2023-12-11 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_order_delivery_type_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('Завершён', 'completed'), ('Готовится', 'cooking'), ('Отменён', 'cancelled'), ('Доставка', 'delivery')], default='Cамовывоз', max_length=9),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Завершён', 'completed'), ('Готовится', 'cooking'), ('Отменён', 'cancelled'), ('Доставка', 'delivery')], default='Готовится', max_length=9),
        ),
    ]
