# Generated by Django 4.2.7 on 2023-12-12 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_order_order_delivered_time_order_order_ready_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_delivered_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_ready_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
