# Generated by Django 4.2.7 on 2023-12-12 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_order_order_delivered_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_delivered_time',
            new_name='delivered_time',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_ready_time',
            new_name='ready_time',
        ),
    ]
