# Generated by Django 4.2.7 on 2023-12-12 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rename_order_delivered_time_order_delivered_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('Cамовывоз', 'pickup'), ('Доставка', 'delivery')], default='Cамовывоз', max_length=9),
        ),
    ]
